---
- hosts: cluster-nodes
  remote_user: adminuser
  # become_method: sudo
  # connection: ssh
  become: yes
  roles:
    - common
# - hosts: new-nodes
#   remote_user: adminuser
#   # become_method: sudo
#   # connection: ssh
#   become: yes
#   roles:
#     - common
